apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: non-namespaced-resources-reader
rules:
- apiGroups: [""]
  resources: ["node", "clusterrole", "clusterrolebinding", "namespace"]
  verbs: ["get", "watch", "list"]
