apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev1-app1-ns-single-namespace-resources-contributor
  namespace: app1-ns
subjects:
- kind: ServiceAccount
  name: dev1 # Name is case sensitive
  namespace: default # Needs to be added only for service accounts
roleRef:
  kind: ClusterRole
  name: single-namespace-resources-contributor
  apiGroup: rbac.authorization.k8s.io
