apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: single-namespace-resources-contributor
rules:
- api_groups = ["aadpodidentity.k8s.io", "apps", "autoscaling", "batch", "extensions", "events.k8s.io", 
                    "networking.k8s.io", "metrics.k8s.io", "secrets-store.csi.x-k8s.io""]
  resources  = ["*"]
  verbs      = ["*"]
